export const PLATFORMS = [
  {
    id: 'linkedin',
    name: 'LinkedIn',
    color: '#0A66C2',
    initials: 'Li',
    searchUrl: (q) => `https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.linkedin.com/jobs/',
  },
  {
    id: 'glassdoor',
    name: 'Glassdoor',
    color: '#0CAA41',
    initials: 'Gd',
    searchUrl: (q) => `https://www.glassdoor.com/Job/jobs.htm?sc.keyword=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.glassdoor.com/Job/index.htm',
  },
  {
    id: 'indeed',
    name: 'Indeed',
    color: '#2164F3',
    initials: 'In',
    searchUrl: (q) => `https://www.indeed.com/jobs?q=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.indeed.com/',
  },
  {
    id: 'google',
    name: 'Google Jobs',
    color: '#4285F4',
    initials: 'Go',
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent(q + ' jobs')}&ibp=htl;jobs`,
    homeUrl: 'https://www.google.com/search?q=jobs&ibp=htl;jobs',
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    color: '#e05c30',
    initials: 'Wf',
    searchUrl: (q) => `https://wellfound.com/jobs?query=${encodeURIComponent(q)}`,
    homeUrl: 'https://wellfound.com/jobs',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    color: '#3ABF6E',
    initials: 'Gh',
    searchUrl: () => `https://job-boards.greenhouse.io/`,
    homeUrl: 'https://job-boards.greenhouse.io/',
  },
  {
    id: 'alljobs',
    name: 'AllJobs',
    color: '#E8462A',
    initials: 'AJ',
    searchUrl: (q) => `https://www.alljobs.co.il/SearchResultsGuest.aspx?position=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.alljobs.co.il/',
    isLocal: true,
  },
  {
    id: 'jobmaster',
    name: 'JobMaster',
    color: '#003B7A',
    initials: 'JM',
    searchUrl: (q) => `https://www.jobmaster.co.il/jobs/?q=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.jobmaster.co.il/',
    isLocal: true,
  },
  {
    id: 'drushim',
    name: 'Drushim',
    color: '#FF6600',
    initials: 'Dr',
    searchUrl: (q) => `https://www.drushim.co.il/jobs/search/?q=${encodeURIComponent(q)}`,
    homeUrl: 'https://www.drushim.co.il/',
    isLocal: true,
  },
]

export const PLATFORM_BY_ID = Object.fromEntries(PLATFORMS.map(p => [p.id, p]))
export const PLATFORM_BY_NAME = Object.fromEntries(PLATFORMS.map(p => [p.name.toLowerCase(), p]))
