-- ══════════════════════════════════════════════════════════════════════════
-- Phase 3: Interview Knowledge Base
--
-- Three normalized tables that form the evidence layer under company profiles:
--
--   company_intel_sources   raw evidence records (AI, users, future scrapers)
--   company_questions       de-duplicated question library keyed by company
--   interview_stage_reports user-submitted stage outcomes (feeds the library)
--
-- Data flow (today):
--   buildInterviewProfile → company_questions (ai_generated, confidence 0.50)
--   reportInterviewStage  → company_intel_sources → company_questions
--                                                     (user_report, conf 0.85)
--
-- Data flow (future scraping):
--   Reddit / Glassdoor Edge Fn → company_intel_sources → company_questions
--                                                        (scraped, conf 0.70)
--   Aggregate patterns from interview_stage_reports → company_intel_sources
--                                                     (platform_signal, conf 0.90)
-- ══════════════════════════════════════════════════════════════════════════


-- ── 1. company_intel_sources ──────────────────────────────────────────────
-- One row per piece of raw evidence. All upstream of both company_questions
-- and company_knowledge. The source_type enum controls ingestion path logic.

CREATE TABLE IF NOT EXISTS company_intel_sources (
  id                  uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  company_key         text    NOT NULL,

  -- Who produced this evidence
  source_type         text    NOT NULL
    CHECK (source_type IN (
      'ai_inferred',    -- generated by our own AI (lowest trust)
      'user_report',    -- submitted by a Job Maker user
      'reddit',         -- scraped from Reddit (future)
      'glassdoor',      -- scraped from Glassdoor (future)
      'linkedin',       -- scraped from LinkedIn posts (future)
      'company_blog',   -- scraped from company engineering/hiring blog (future)
      'news',           -- news article or press release (future)
      'platform_signal' -- aggregated from our own hiring_events data
    )),

  source_url          text,                   -- null for ai_inferred / user_report
  source_title        text,
  source_date         date,                   -- publication date; null if unknown
  scraped_at          timestamptz DEFAULT now(),

  -- Normalized evidence payload — shape varies by source_type
  extracted_findings  jsonb   NOT NULL DEFAULT '{}',

  -- 0.0–1.0 scale
  -- ai_inferred ≤ 0.55, user_report ≈ 0.85, reddit/glassdoor ≈ 0.70,
  -- platform_signal ≈ 0.90
  confidence          numeric(3,2) NOT NULL DEFAULT 0.50
    CHECK (confidence BETWEEN 0 AND 1),

  -- Searchable tags: 'interview_process', 'culture', 'questions', 'onsite', etc.
  relevance_tags      text[]  NOT NULL DEFAULT '{}',

  contributed_by      uuid    REFERENCES auth.users(id) ON DELETE SET NULL,

  status              text    NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'stale', 'disputed'))
);

CREATE INDEX IF NOT EXISTS idx_intel_sources_company
  ON company_intel_sources (company_key, source_type);
CREATE INDEX IF NOT EXISTS idx_intel_sources_tags
  ON company_intel_sources USING GIN (relevance_tags);

ALTER TABLE company_intel_sources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "intel_sources_select" ON company_intel_sources
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "intel_sources_insert" ON company_intel_sources
  FOR INSERT TO authenticated WITH CHECK (true);


-- ── 2. company_questions ─────────────────────────────────────────────────
-- De-duplicated question library. A generated column (question_normalized)
-- enables exact-text deduplication across sources. Near-duplicate merging
-- via embeddings is a future task.

CREATE TABLE IF NOT EXISTS company_questions (
  id                  uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  company_key         text    NOT NULL,

  -- Normalized lookup key for deduplication (lower-trimmed question text)
  question_normalized text    GENERATED ALWAYS AS (lower(trim(question))) STORED,

  -- Broad role grouping. NULL means "all roles".
  -- Values: engineering | product | design | data | ops | sales | marketing
  role_family         text,

  -- Which interview stage this question belongs to.
  -- Values: recruiter_screen | hiring_manager | technical | culture |
  --         case_study | panel | general
  stage               text,

  question            text    NOT NULL,

  -- Which source record this first came from (nullable: AI-seeded rows have no source)
  source_id           uuid    REFERENCES company_intel_sources(id) ON DELETE SET NULL,

  -- How many times this question (or an exact duplicate) has been reported
  frequency           int     NOT NULL DEFAULT 1,

  confidence          numeric(3,2) NOT NULL DEFAULT 0.50
    CHECK (confidence BETWEEN 0 AND 1),

  is_ai_generated     boolean NOT NULL DEFAULT false,

  created_at          timestamptz DEFAULT now(),
  updated_at          timestamptz DEFAULT now(),

  -- Exact-text deduplication per company + stage
  UNIQUE (company_key, question_normalized, stage)
);

CREATE INDEX IF NOT EXISTS idx_company_questions_lookup
  ON company_questions (company_key, role_family, stage);
CREATE INDEX IF NOT EXISTS idx_company_questions_freq
  ON company_questions (company_key, frequency DESC);

ALTER TABLE company_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "company_questions_select" ON company_questions
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "company_questions_insert" ON company_questions
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "company_questions_update" ON company_questions
  FOR UPDATE TO authenticated USING (true);


-- ── 3. interview_stage_reports ────────────────────────────────────────────
-- User-submitted stage progression. One row per (user, job, stage).
-- This is the primary first-party signal that will eventually make
-- company_questions high-confidence without any web scraping.
--
-- Privacy: users see only their own reports (RLS below).
-- Aggregated signals are materialized into company_intel_sources separately.

CREATE TABLE IF NOT EXISTS interview_stage_reports (
  id              uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id          uuid    NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  company_key     text    NOT NULL,
  role_family     text,

  -- Which stage is being reported
  stage_name      text    NOT NULL
    CHECK (stage_name IN (
      'recruiter_screen', 'hiring_manager', 'technical',
      'culture', 'case_study', 'panel', 'offer', 'rejection'
    )),

  outcome         text
    CHECK (outcome IN ('passed', 'rejected', 'pending', 'withdrew')),

  duration_min    int,                  -- how long the stage took
  questions_seen  text[]  DEFAULT '{}', -- questions the user remembered being asked
  notes           text,
  reported_at     timestamptz DEFAULT now(),

  -- One report per stage per job per user (can update via upsert)
  UNIQUE (user_id, job_id, stage_name)
);

CREATE INDEX IF NOT EXISTS idx_stage_reports_company
  ON interview_stage_reports (company_key, stage_name, outcome);

ALTER TABLE interview_stage_reports ENABLE ROW LEVEL SECURITY;
-- Users read/write only their own reports
CREATE POLICY "stage_reports_own"
  ON interview_stage_reports FOR ALL
  TO authenticated
  USING      (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- ── 4. RPC: upsert_company_question ──────────────────────────────────────
-- Called from the app for every question we want to add to the library.
-- On exact-text collision: increments frequency and raises confidence to
-- the higher of the two values.

CREATE OR REPLACE FUNCTION upsert_company_question(
  p_company_key       text,
  p_role_family       text,
  p_stage             text,
  p_question          text,
  p_source_id         uuid,
  p_confidence        numeric,
  p_is_ai_generated   boolean
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  INSERT INTO company_questions
    (company_key, role_family, stage, question, source_id, confidence, is_ai_generated, frequency)
  VALUES
    (p_company_key, p_role_family, p_stage, p_question, p_source_id, p_confidence, p_is_ai_generated, 1)
  ON CONFLICT (company_key, question_normalized, stage)
  DO UPDATE SET
    frequency   = company_questions.frequency + 1,
    confidence  = GREATEST(company_questions.confidence, EXCLUDED.confidence),
    source_id   = COALESCE(company_questions.source_id, EXCLUDED.source_id),
    updated_at  = now();
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION upsert_company_question TO authenticated;
